# Generated by Django 3.0 on 2020-06-01 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoList_App', '0002_auto_20200601_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='slug',
            field=models.SlugField(default='slug', unique=True),
        ),
    ]
