# Generated by Django 3.0 on 2020-06-02 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoList_App', '0003_tasks_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='is_InProgress',
            field=models.BooleanField(default=True),
        ),
    ]
