# Generated by Django 3.0 on 2020-06-02 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoList_App', '0004_auto_20200602_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='slug',
        ),
    ]
